from enum import Enum, auto

import pandas as pd


class Diseases(Enum):
    ABSCESS = auto()
    ACUTE_DISSEMINATED_ENCEPHALOMYELITIS = auto()
    ACUTE_HEMORRHAGIC_LEUKOENCEPHALITIS = auto()
    AIDS_HIV_ENCEPHALITIS = auto()
    ALZHEIMER_DISEASE = auto()
    AMYLOID_ANGIOPATHY = auto()
    ANEURYSM = auto()
    ANEURYSM_THROMBOSED = auto()
    ANGIOMATOSIS_LEPTOMENINGEAL = auto()
    ARACHNOID_CYST = auto()
    ARTERIOVENOUS_MALFORMATION_OR_FISTULA = auto()
    ASTROCYTOMA_HIGH_GRADE = auto()
    ASTROCYTOMA_LOW_GRADE = auto()
    BEHCET = auto()
    CADASIL = auto()
    CAPILLARY_TELANGIECTASIA = auto()
    CAVERNOUS_MALFORMATION = auto()
    CEPHALOCELE = auto()
    CEREBRITIS = auto()
    CHIARI_MALFORMATION = auto()
    CHOROID_PLEXUS_PAPILLOMA_OR_CARCINOMA = auto()
    COLLOID_CYST = auto()
    CONTUSION_CEREBRAL = auto()
    CORTICAL_DYSYPLASIA = auto()
    CRANIOPHARYNGIOMA = auto()
    CRYPTOCOCCOSIS = auto()
    CYSTICERCOSIS = auto()
    CYTOMEGALOVIRUS = auto()
    DANDY_WALKER_MALFORMATION_SPECTRUM = auto()
    DERMOID = auto()
    DIFFUSE_AXONAL_INJURY = auto()
    DYSEMBROPLASTIC_NEUROEPITHELIAL_TUMOR = auto()
    EMPYEMA_SUBDURAL_EPIDURAL = auto()
    ENCEPHALITIS = auto()
    ENCEPHALOMALACIA = auto()
    EPENDYMAL_TUMORS = auto()
    EPIDERMOID_CYST = auto()
    EPILEPSY_SEIZURES = auto()
    FAHR_DISEASE = auto()
    FOREIGN_BODY = auto()
    FRONTOTEMPORAL_DEGENERATION = auto()
    GANGLIOCYTOMA_GANGLIOGLIOMA = auto()
    GERMINOMA = auto()
    GIANT_CELL_ASTROCYTOMA = auto()
    GLIOBLASTOMA = auto()
    GLIOMATOSIS_CEREBRI = auto()
    GLIOSIS = auto()
    HAMARTOMA_OF_TUBER_CINEREUM = auto()
    HEMANGIOBLASTOMA = auto()
    HEMANGIOPERICYTOMA = auto()
    HEMATOMA_INTRACEREBRAL_ACUTE = auto()
    HEMATOMA_INTRACEREBRAL_CHRONIC = auto()
    HEMATOMA_INTRACEREBRAL_SUBACUTE = auto()
    HEMATOMA_INTRAVENTRICULAR_ACUTE = auto()
    HEMATOMA_SUBDURAL_EPIDURAL_ACUTE = auto()
    HEMATOMA_SUBDURAL_EPIDURAL_CHRONIC = auto()
    HEMATOMA_SUBDURAL_EPIDURAL_SUBACUTE = auto()
    HEMOSIDEROSIS_LEPTOMENINGEAL = auto()
    HEPATIC_ENCEPHALOPATHY = auto()
    HERPES_SIMPLEX_ENCEPHALITIS = auto()
    HETEROTYPIC_GRAY_MATTER = auto()
    HUNTINGTON_DISEASE = auto()
    HYDROCEPHALUS_COMMUNICATING = auto()
    HYDROCEPHALUS_NONCOMMUNICATING = auto()
    HYGROMA_SUBDURAL = auto()
    HYPOXIC_ISCHEMIC_ENCEPHALOPATHY = auto()
    INFARCTION_ACUTE = auto()
    INFARCTION_CHRONIC = auto()
    INFARCTION_SUBACUTE = auto()
    JAKOB_CREUTZFELDT_DISEASE = auto()
    LHERMITTE_DUCLOS_DISEASE = auto()
    LIPOMA = auto()
    LYME_DISEASE = auto()
    LYMPHOMA = auto()
    MEDULLOBLASTOMA = auto()
    MENINGIOMA = auto()
    MENINGITIS = auto()
    MESIAL_TEMPORAL_SCLEROSIS = auto()
    METABOLIC_POISONING = auto()
    METASTASIS_INTRACEREBRAL = auto()
    METASTASIS_LEPTOMENINGEAL = auto()
    MIGRAINE = auto()
    MITOCHONDRIAL_DISEASE = auto()
    MOYAMOYA_DISEASE = auto()
    MULTIPLE_SCLEROSIS = auto()
    MULTIPLE_SCLEROSIS_TUMEFACTIVE_DEMYELINATING = auto()
    MULTIPLE_SYSTEM_ATROPHY = auto()
    MYELINOLYSIS_ACUTE_CENTRAL_PONTINE = auto()
    MYELINOLYSIS_EXTRAPONTINE = auto()
    NEUROCYTOMA_CENTRAL = auto()
    NEUROFIBROMATOSIS_TYPE_1 = auto()
    NEUROFIBROMATOSIS_TYPE_2 = auto()
    NORMAL = auto()
    OLIGODENDROGLIOMA = auto()
    PARKINSON_PLUS = auto()
    PERIVENTRICULAR_LEUKOMALACIA = auto()
    PINEAL_NEOPLASM = auto()
    PLEOMORPHIC_XANTHOASTROCYTOMA = auto()
    PNEUMOCEPHALUS = auto()
    PORENCEPHALIC_CYST = auto()
    POSTERIOR_REVERSIBLE_ENEPHALOPATHY = auto()
    PRIMITIVE_NEUROECTODERMAL_TUMOR = auto()
    PROGRESSIVE_MULTIFOCAL_LEUKOENCEPHALOPATHY = auto()
    PSEUDOTUMOR = auto()
    RHOMBENCEPHALITIS = auto()
    SARCOIDOSIS = auto()
    SCHIZENCEPHALY = auto()
    SCHWANNOMA = auto()
    SMALL_VESSEL_ISCHEMIC_CHANGES = auto()
    SUBARACHNOID_HEMORRHAGE = auto()
    SYRINGOBULBIA = auto()
    TERATOMA = auto()
    THROMBOEMBOLISM_ARTERIAL = auto()
    THROMBOSIS_VENOUS = auto()
    TOXOPLASMOSIS = auto()
    TUBERCULOSIS = auto()
    TUBEROUS_SCLEROSIS = auto()
    VASCULITIS = auto()
    VENTRICULITIS_EPENDYMITIS = auto()
    WALLERIAN_DEGENERATION = auto()
    WERNICKE_ENCEPHALOPATHY = auto()
    WILSON_DISEASE = auto()


if __name__ == "__main__":
    with open(r"C:\Users\dhruv\git\radiology-nlp\data\unlabeled_neuro_reports\diseases.csv", "r") as f:
        kf = pd.read_csv(f)

    # set(list(kf["ddx1"]) + list(kf["ddx2"]) + list(kf["ddx3"])):
    for d in set(kf["ergo_name"]):
        print(d.upper() + " = auto()")
